::#region Mount Images
DISM /Mount-Image /ImageFile:"C:\TMP\install.wim" /index:6 /mountdir:"C:\Mount\Windows"
DISM /Mount-Image /ImageFile:"C:\Mount\Windows\Windows\System32\Recovery\Winre.wim" /Index:1 /MountDir:"C:\Mount\WinRE"
::#endregion

::#region Add FoD English (No changes)
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-Basic-en-us-Package~31bf3856ad364e35~amd64~~.cab"
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-OCR-en-us-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-Handwriting-en-us-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-TextToSpeech-en-us-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-Speech-en-us-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /packagepath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-RetailDemo-OfflineContent-Content-en-us-Package~31bf3856ad364e35~amd64~~.cab"
::#endregion

::#region Add FoD Japanese (No changes)
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguagePacks\x64\langpacks\Microsoft-Windows-Client-Language-Pack_x64_ja-jp.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-Basic-ja-jp-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-OCR-ja-jp-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-Handwriting-ja-jp-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-TextToSpeech-ja-jp-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-LanguageFeatures-Speech-ja-jp-Package~31bf3856ad364e35~amd64~~.cab" 
DISM /Add-Package /Image:C:\Mount\Windows /packagepath:"C:\TMP\LanguageFeaturePacks\amd64\Microsoft-Windows-RetailDemo-OfflineContent-Content-ja-jp-Package~31bf3856ad364e35~amd64~~.cab"
::#endregion

::#region Add Languages for Recovery - Japanese (No changes - I have shortended the path name for "WinPE". In OPK it is "Windows Preinstallation Environment")
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\lp.cab"
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\WinPE-FontSupport-JA-JP.cab"
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-Rejuv_ja-jp.cab"
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-EnhancedStorage_ja-jp.cab"
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-Scripting_ja-jp.cab"
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-SecureStartup_ja-jp.cab" 
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-SRT_ja-jp.cab" 
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-WDS-Tools_ja-jp.cab" 
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-WMI_ja-jp.cab" 
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-StorageWMI_ja-jp.cab" 
DISM /Image:C:\Mount\WinRE /Add-Package /PackagePath:"C:\TMP\LanguagePacks\WinPE\x64\WinPE_OCs\ja-jp\WinPE-HTA_ja-jp.cab"
::#endregion

::#region Set Language Defaults (No changes)
REM DISM /Image:C:\Mount\Windows /Set-AllIntl:en-us
REM DISM /Image:C:\Mount\WinRE /Set-AllIntl:en-us
DISM /Image:C:\Mount\Windows /Set-AllIntl:ja-jp
DISM /Image:C:\Mount\WinRE /Set-AllIntl:ja-jp
DISM /Image:C:\Mount\WinRE /Get-Intl
DISM /Image:C:\Mount\Windows /Set-TimeZone:"Tokyo Standard Time"
REM DISM /Image:C:\Mount\Windows /Set-TimeZone:"Hawaiian Standard Time"
REM DISM /Image:C:\Mount\Windows /Set-TimeZone:"Pacific Standard Time"
::#endregion

::#region Configure Recovery & StartLayout
MD C:\Mount\Windows\Recovery\OEM
MD C:\Mount\Windows\Recovery\Customizations
XCopy C:\TMP\Recovery C:\Mount\Windows\Recovery\OEM
REM XCopy C:\TMP\Recovery\layoutmodification.xml C:\Mount\Windows\Users\Default\AppData\Local\Microsoft\Windows\Shell\
::#endregion

::#region Updates (No changes) - Don't forget to update KB# with latest update from http://www.catalog.update.microsoft.com/Search.aspx?q=windows%2010%20version%201903%20cumulative%20update
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\Updates\amd64\windows10.0-kb4495666-x64_9a38cfd2baecbf99be7ce4348d9bf866d7ea9eeb.msu"
DISM /Add-Package /Image:C:\Mount\Windows /PackagePath:"C:\TMP\Updates\amd64\windows10.0-kb4497093-x64_196627b1499cdcc002aeb64172cd3eb0bfc581bb.msu"
:: KB.msu doesn't work for WinRE - skip adding it but test for future updates
REM DISM /Add-Package /Image:C:\Mount\WinRE /PackagePath:"C:\TMP\Updates\amd64\windows10.0-kb4495666-x64_9a38cfd2baecbf99be7ce4348d9bf866d7ea9eeb.msu"
::#endregion

::#region Appx Updates - Changes to dependencies in 1903 - There are no new appx bundles
:: removed  - Microsoft.Services.Store.Engagement.x86.appx 

:: removed  - Microsoft.NET.Native.Runtime.x86.1.6.appx
:: removed  - Microsoft.NET.Native.Runtime.x64.1.6.appx
:: removed  - Microsoft.NET.Native.Framework.x86.1.6.appx
:: removed  - Microsoft.NET.Native.Framework.x64.1.6.appx

:: added    - Microsoft.UI.Xaml.x64.2.0.appx 
:: added    - Microsoft.VCLibs.x64.14.00.Desktop.appx

:: added    - Microsoft.NET.Native.Framework.x64.2.2.appx
:: added    - Microsoft.NET.Native.Runtime.x64.2.2.appx

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.BingWeather_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.BingWeather_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.GetHelp_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.GetHelp_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Getstarted_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Getstarted_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Messaging_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Messaging_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Microsoft3DViewer_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Microsoft3DViewer_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.MSPaint_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.MSPaint_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Office.OneNote_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Office.OneNote_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.OneConnect_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.OneConnect_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.People_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.People_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Print3D_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Print3D_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.SkypeApp_kzf8qxf38zg5c.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.SkypeApp_kzf8qxf38zg5c.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.StorePurchaseApp_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.StorePurchaseApp_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Wallet_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Wallet_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Windows.Photos_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Windows.Photos_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsAlarms_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsAlarms_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"  

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsCalculator_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsCalculator_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsCamera_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsCamera_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsCommunicationsApps_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsCommunicationsApps_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsMaps_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsMaps_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsStore_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.WindowsStore_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Xbox.TCUI_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.Xbox.TCUI_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxApp_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxApp_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxGameOverlay_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxGameOverlay_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx" 

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.ZuneMusic_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.ZuneMusic_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.ZuneVideo_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.ZuneVideo_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.HEVCVideoExtension_8wekyb3d8bbwe.x64.appx" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.HEVCVideoExtension_8wekyb3d8bbwe.x64.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.MixedReality.Portal_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.MixedReality.Portal_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.ScreenSketch_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.ScreenSketch_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"

DISM /Add-ProvisionedAppxPackage /image:"C:\Mount\Windows" /PackagePath:"C:\TMP\Apps\amd64fre\Microsoft.YourPhone_8wekyb3d8bbwe.appxbundle" /LicensePath:"C:\TMP\Apps\amd64fre\Microsoft.YourPhone_8wekyb3d8bbwe.xml" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x86.14.00.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x86.1.7.appx"  /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Framework.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.2.2.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x64.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.NET.Native.Runtime.x86.1.7.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.Services.Store.Engagement.x64.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.UI.Xaml.x64.2.0.appx" /DependencyPackagePath:"C:\TMP\Apps\amd64fre\Microsoft.VCLibs.x64.14.00.Desktop.appx"
::#endregion

::#region Cleanup, Commit, and Export
DISM /Image:"C:\Mount\WinRE" /Cleanup-Image /AnalyzeComponentStore
DISM /Image:"C:\Mount\WinRE" /Cleanup-Image /StartComponentCleanup /ResetBase
DISM /Unmount-Image /MountDir:"C:\Mount\WinRE" /Commit

DISM /Export-Image /SourceImageFile:"C:\Mount\Windows\Windows\System32\Recovery\WinRE.wim" /SourceIndex:1 /DestinationImageFile:"C:\TMP\WinRE_Bak.wim"
DEL C:\Mount\Windows\Windows\System32\Recovery\WinRE.wim
COPY C:\TMP\WinRE_Bak.wim C:\Mount\Windows\Windows\System32\Recovery\WinRE.wim
REM DEL C:\TMP\WinRE_Bak.wim

DISM /Image:"C:\Mount\Windows" /Cleanup-Image /AnalyzeComponentStore
DISM /Image:"C:\Mount\Windows" /Cleanup-Image /StartComponentCleanup /ResetBase
DISM /Unmount-Image /MountDir:"C:\Mount\Windows" /Commit

DISM /Export-Image /SourceImageFile:"C:\TMP\install.wim" /SourceIndex:6 /DestinationImageFile:"C:\TMP\amd64-EN-JA-Pro.wim"
DISM /Get-WimInfo /WimFile:"C:\TMP\amd64-EN-JA-Pro.wim" /Index:1
::#endregion

:EOF
